kind: pipeline
name: default

steps:
- name: build
  image: alpine
  environment:
    USERNAME:
      from_secret: username
  commands:
  # - echo "Hi from elk!"
  - echo $${USERNAME}
  - echo $${DRONE_COMMIT_AUTHOR}
    # - env
---
kind: secret
name: username
get:
  path: secret/data/docker
  name: username
