---
kind: pipeline
type: docker

steps:
  - name: test
    image: bash
    environment:
      USERNAME:
        from_secret: username
    commands:
      - printf "$$USERNAME"

---
kind: secret
name: username
get:
  path: secret/docker
  name: username