---
kind: pipeline
type: docker

steps:
  - name: test
    image: bash
    commands:
      # - my-command > plugin-script.sh
      - printf "Hello from elk ivanpap18"
    when:
      branch:
        - main
trigger:
  branch:
    - main   
  event:
    - push
    - tag
