kind: pipeline
name: default

steps:
- name: build
  image: alpine
  environment:
    USERNAME:
      from_secret: username
  commands:
  - env
---
kind: secret
name: username
get:
  path: /secret/data/docker
  name: username
