kind: pipeline
name: default

steps:
- name: build
  image: alpine
  environment:
    USERNAME:
      from_secret: username
  commands:
  - echo "hi there"
  - echo ${USERNAME}

---
kind: secret
name: username
get:
  path: secrets/data/docker
  name: username
