---
kind: pipeline
type: docker

steps:
  - name: test
    image: bash
    environment:
    USERNAME:
      from_secret: username
    commands:
      - echo $USERNAME
    # commands:
    #   - printf "Hello world!"
    when:
      branch: 
        - main     
---
kind: secret
name: password
get:
  path: v1/secrets/data/docker
  name: username
  
trigger:
  branch:
    - main 
  event:
    - push
    - tag   
