---
kind: pipeline
type: docker

steps:
  - name: test
    image: bash
    commands:
      # - my-command > plugin-script.sh
      - printf "Hello from elk ivanpap18"
    when:
      branch:
        - master
trigger:
  branch:
    - master
    
  event:
    - push
    - tag   
