---
kind: pipeline
type: docker

steps:
  - name: test
    image: bash
    commands:
      - printf "Hello from devtools"
    when:
      branch:
        - master
trigger:
  branch:
    - master
  event:
    - push
    - tag  
