filebeat.inputs:
- type: filestream
  id: my_filestream_id
  paths:
  - /var/log/*.log

- type: container
  paths:
  - '/var/lib/docker/containers/*/*.log'
  processors:
  - add_docker_metadata: ~
output.elasticsearch:
  hosts: ["https://es01:9200"]
  username: "elastic"
  password: "PleaseChangeMe"
  index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
  # ssl.verification_mode: none
  ssl.certificate_authorities: "/usr/share/filebeat/config/certs/ca/ca.crt"
  ssl.certificate: "/usr/share/filebeat/config/certs/es01/es01.crt"
  ssl.key: "/usr/share/filebeat/config/certs/es01/es01.key"

setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"

# setup.kibana.hosts: "https://kibana:5601"
# setup.kibana.username: "elastic"
# setup.kibana.password!: "PleaseChangeMe"