#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
# ------------------------------------------------------------------------------
# Website: https://vector.dev
# Docs: https://vector.dev/docs
# Chat: https://chat.vector.dev
# ------------------------------------------------------------------------------

#LANCE MULTIPLE CONFIG  
# vector --config vector1.toml --config vector2.toml

# GLOBBING SYNTAX
# vector --config /etc/vector/*.toml

# MULTIPLE TRANSFORMATIONS
# inputs = ["ma_source_1", "ma_source_2"]

# Default directory for Vector data storage:
data_dir = "${DATA_DIR}"

# Vector's GraphQL API (disabled by default)
# Uncomment to try it out with the `vector top` command or
# in your browser at http://localhost:8686
[api]
  enabled = true
  # address = "127.0.0.1:8686"

[sources.logs_flexibranche]
  type = "docker_logs"
  include_containers = ["flexibranche_dev"]

# [transforms.april-contracts] 
#   type = "remap"
#   inputs = ["logs_april_docker"]
#   source = """
#     .info, err = strip_ansi_escape_codes(.info)
#   """

# [transforms.april-products] 
#   type = "remap"
#   inputs = ["logs_april_docker"]
#   source = """
#     .info, err = strip_ansi_escape_codes(.info)
#   """

[transforms.flexibranche_all] 
  type = "remap"
  inputs = ["logs_flexibranche"]
  source = """ 
    del(.label)
    del(.container_id)
    del(.host)
    del(.image)
    del(.container_created_at)
    .message, err = strip_ansi_escape_codes(.message)
    .service = del(.container_name)
    del(.source_type)
    del(.stream)
  """

# //CONSOLE
[sinks.logs_flexibranche_to_console]
  type = "console"
  inputs = ["flexibranche_all"]
  target = "stdout"

    [sinks.logs_flexibranche_to_console.encoding]
    codec = "json"
    
#//ELASTIC APRIL
[sinks.logs_flexibranche_to_elastic]
  type = "elasticsearch"
  inputs = ["flexibranche_all"]
  pipeline = "Logs_Flexibranche"
  compression = "none"
  endpoint = "${END_POINT}"
  tls.crt_file = "${CRT_FILE}"
  tls.key_file= "${KEY_FILE}"
  tls.ca_file= "${CA_FILE}"
  auth.user = "${ELASTIC_USERNAME}"
  auth.password = "${ELASTIC_PASSWORD}"
  auth.strategy = "${LICENSE}"
  suppress_type_name = true
  mode = "data_stream"
  data_stream.type = "logs"
  data_stream.dataset = "docker"
  data_stream.namespace = "flexibranche-dev"